const notifications = [
  {
    id: 1,
    username: "Mark Webber",
    time: "1m ago",
    avatar: "/images/avatar-mark-webber.webp",
    action: "reacted to your recent post",
    target: "My first tournament today!",
    targetImage: "",
    isUnread: true,
    isClub: false,
    isBold: true,
    privateMessage: false,
  },
  {
    id: 2,
    username: "Angela Gray",
    time: "5m ago",
    avatar: "/images/avatar-angela-gray.webp",
    action: "followed you",
    target: "",
    targetImage: "",
    isUnread: true,
    isClub: false,
    isBold: false,
    privateMessage: false,
  },
  {
    id: 3,
    username: "Jacob Thompson",
    time: "1 day ago",
    avatar: "/images/avatar-jacob-thompson.webp",
    action: "has joined your group",
    target: "Chess Club",
    targetImage: "",
    isUnread: true,
    isClub: true,
    isBold: true,
    privateMessage: false,
  },
  {
    id: 4,
    username: "Rizky Hasanuddin",
    time: "5 days ago",
    avatar: "/images/avatar-rizky-hasanuddin.webp",
    action: "sent you a private message",
    target:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    targetImage: "",
    isUnread: false,
    isClub: false,
    isBold: false,
    privateMessage: true,
  },
  {
    id: 5,
    username: "Kimberly Smith",
    time: "1 week ago",
    avatar: "/images/avatar-kimberly-smith.webp",
    action: "commented on your picture",
    target: "",
    targetImage: "/images/image-chess.webp",
    isUnread: false,
    isClub: false,
    isBold: false,
    privateMessage: false,
  },
  {
    id: 6,
    username: "Nathan Peterson",
    time: "2 weeks ago",
    avatar: "images/avatar-nathan-peterson.webp",
    action: "reacted to your recent post",
    target: "5 end-game strategies to increase your win rate",
    targetImage: "",
    isUnread: false,
    isClub: false,
    isBold: true,
    privateMessage: false,
  },
  {
    id: 7,
    username: "Anna Kim",
    time: "2 weeks ago",
    avatar: "/images/avatar-anna-kim.webp",
    action: "left the group",
    target: "Chess Club",
    targetImage: "",
    isUnread: false,
    isClub: true,
    isBold: true,
    privateMessage: false,
  },
];

export default notifications;
